[2020-07-13 23:21:30,628] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: news_fetch.push_s3 2020-07-11T01:20:00+00:00 [queued]>
[2020-07-13 23:21:30,637] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: news_fetch.push_s3 2020-07-11T01:20:00+00:00 [queued]>
[2020-07-13 23:21:30,637] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 23:21:30,637] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-07-13 23:21:30,637] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-13 23:21:30,644] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): push_s3> on 2020-07-11T01:20:00+00:00
[2020-07-13 23:21:30,649] {standard_task_runner.py:53} INFO - Started process 27643 to run task
[2020-07-13 23:21:30,688] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: news_fetch.push_s3 2020-07-11T01:20:00+00:00 [running]> tony-ThinkPad-X1-Carbon-7th
[2020-07-13 23:21:30,737] {taskinstance.py:1145} ERROR - Parameter validation failed:
Invalid bucket name "tennisvideobucket/input-vid/images": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
Traceback (most recent call last):
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "airflow_home//dags/s3_push.py", line 26, in upload_file
    response = s3_client.upload_file(file_name, bucket, object_name)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 654, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/client.py", line 686, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/tony/.virtualenvs/cv/lib/python3.6/site-packages/botocore/handlers.py", line 205, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "tennisvideobucket/input-vid/images": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2020-07-13 23:21:30,738] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=news_fetch, task_id=push_s3, execution_date=20200711T012000, start_date=20200713T152130, end_date=20200713T152130
[2020-07-13 23:21:40,620] {logging_mixin.py:112} INFO - [2020-07-13 23:21:40,620] {local_task_job.py:103} INFO - Task exited with return code 1
